apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-service
  type: {{ .Values.hello.service.type }}
  ports:
    - port: {{ .Values.hello.service.port }}
      targetPort: 5001
