apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: "{{ .Values.profile.image.repository }}:{{ .Values.profile.image.tag }}"
        imagePullPolicy: {{ .Values.profile.image.pullPolicy }}
        ports:
        - containerPort: 5002
