apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  type: {{ .Values.profile.service.type }}
  ports:
    - port: {{ .Values.profile.service.port }}
      targetPort: 5002
